image: amazon/aws-sam-cli-build-image-nodejs14.x:latest

stages:
  - deploy

variables:
  STACK_NAME: api-query-rds
  REGION: eu-west-2

deploy:
  image: amazon/aws-sam-cli-build-image-nodejs14.x:latest
  stage: deploy
  script:
   - sam build
   - sam package --output-template-file packaged.yaml --s3-bucket $S3_DEPLOY_BUCKET --region $REGION
   - sam deploy --no-fail-on-empty-changeset --template-file packaged.yaml --stack-name $STACK_NAME --s3-bucket $S3_DEPLOY_BUCKET --capabilities CAPABILITY_NAMED_IAM --region $REGION
